export * from './principal.entity';
export * from './corrector.entity';
export * from './supervisor.entity';
export * from './secretary.entity';
export * from './student.entity';
export * from './application.entity';
export * from './member.entity';
export * from './planner.entity';
export * from './teacher.entity';
