export * from './add/department-add';
export * from './edit/department-edit';
export * from './form';
export * from './department.module';
export * from './department.service.interface';
export * from './department.service';
export * from './department.resolver';
export * from './banner/department-banner';
export * from './image/department-image';
