export * from './principal.loader';
export * from './corrector.loader';
export * from './supervisor.loader';
export * from './secretary.loader';
export * from './student.loader';
export * from './application.loader';
export * from './member.loader.module';
export * from './planner.loader';
export * from './teacher.loader';
