export * from './authorization.model';
export * from './organisation-model';
export * from './admin.model';
export * from './room.model';
export * from './examination.model';
export * from './principal.model';
export * from './speciality.model';
export * from './group.model';
export * from './student.model';
