// <auto-generated />
using System;
using Exam.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Exam.Migrations
{
    [DbContext(typeof(PersistenceContext))]
    partial class PersistenceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Exam.Entities.Application", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<long>("LevelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LevelSpecialityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ProcessDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LevelId");

                    b.HasIndex("LevelSpecialityId");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasFilter("[StudentId] IS NOT NULL");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Exam.Entities.Contest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PaperId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PaperId");

                    b.ToTable("Contests");
                });

            modelBuilder.Entity("Exam.Entities.Corrector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<int>("PaperCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TestGroupCorrectorCount")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("Correctors");
                });

            modelBuilder.Entity("Exam.Entities.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Coefficient")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGeneral")
                        .HasColumnType("bit");

                    b.Property<long?>("LevelId")
                        .HasColumnType("bigint");

                    b.Property<bool>("MultipleScore")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Radical")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Exam.Entities.CourseLevelSpeciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<long>("LevelSpecialityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("LevelSpecialityId");

                    b.ToTable("CourseLevelSpecialities");
                });

            modelBuilder.Entity("Exam.Entities.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acronym")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasCoverImage")
                        .HasColumnType("bit");

                    b.Property<bool>("HasImage")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrincipalUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Exam.Entities.Examination", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpectedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Examinations");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationDepartment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ExaminationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ExaminationId");

                    b.ToTable("ExaminationDepartments");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ExaminationDepartmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LevelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationDepartmentId");

                    b.HasIndex("LevelId");

                    b.ToTable("ExaminationLevels");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationLevelSpeciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ExaminationLevelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExaminationSpecialityId")
                        .HasColumnType("bigint");

                    b.Property<long>("LevelSpecialityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationLevelId");

                    b.HasIndex("ExaminationSpecialityId");

                    b.HasIndex("LevelSpecialityId");

                    b.ToTable("ExaminationLevelSpecialities");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationSpeciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ExaminationDepartmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SpecialityId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationDepartmentId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("ExaminationSpecialities");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationStudent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ExaminationLevelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExaminationLevelSpecialityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationLevelId");

                    b.HasIndex("ExaminationLevelSpecialityId");

                    b.HasIndex("StudentId");

                    b.ToTable("ExaminationStudents");
                });

            modelBuilder.Entity("Exam.Entities.Level", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("Exam.Entities.LevelSpeciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("LevelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SpecialityId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("LevelSpecialities");
                });

            modelBuilder.Entity("Exam.Entities.Member", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Exam.Entities.Paper", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Anonymity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollectorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContestCount")
                        .HasColumnType("int");

                    b.Property<string>("CorrectorComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ExaminationStudentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("GroupIndex")
                        .HasColumnType("int");

                    b.Property<int>("PaperFileCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<string>("SecretaryComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretaryUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupervisorComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TestGroupCorrectorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TestGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TestGroupSecretaryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TestGroupSupervisorId")
                        .HasColumnType("bigint");

                    b.Property<long>("TestId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TestLevelSpecialityId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationStudentId");

                    b.HasIndex("TestGroupCorrectorId");

                    b.HasIndex("TestGroupId");

                    b.HasIndex("TestGroupSecretaryId");

                    b.HasIndex("TestGroupSupervisorId");

                    b.HasIndex("TestId");

                    b.HasIndex("TestLevelSpecialityId");

                    b.ToTable("Papers");
                });

            modelBuilder.Entity("Exam.Entities.PaperFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Corrected")
                        .HasColumnType("bit");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PaperId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PaperId");

                    b.ToTable("PaperFiles");
                });

            modelBuilder.Entity("Exam.Entities.Planner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<string>("RegisterUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Planners");
                });

            modelBuilder.Entity("Exam.Entities.Principal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<string>("RegisterUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("Principals");
                });

            modelBuilder.Entity("Exam.Entities.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Capacity")
                        .HasColumnType("bigint");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LevelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisterUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LevelId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Exam.Entities.School", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acronym")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasCoverImage")
                        .HasColumnType("bit");

                    b.Property<bool>("HasImage")
                        .HasColumnType("bit");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PrincipalId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PrincipalId1")
                        .HasColumnType("bigint");

                    b.Property<string>("PrincipalUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisterUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalId1");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("Exam.Entities.Score", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Radical")
                        .HasColumnType("float");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Exam.Entities.ScorePaper", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("PaperId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("TestScoreId")
                        .HasColumnType("bigint");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PaperId");

                    b.HasIndex("TestScoreId");

                    b.ToTable("ScorePapers");
                });

            modelBuilder.Entity("Exam.Entities.Secretary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<string>("RegisterUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MemberId");

                    b.ToTable("Secretaries");
                });

            modelBuilder.Entity("Exam.Entities.Speciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Specialities");
                });

            modelBuilder.Entity("Exam.Entities.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<long>("LevelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LevelSpecialityId")
                        .HasColumnType("bigint");

                    b.Property<string>("RegisterUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LevelId");

                    b.HasIndex("LevelSpecialityId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Exam.Entities.Supervisor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MemberId");

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("Exam.Entities.Test", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("Coefficient")
                        .HasColumnType("bigint");

                    b.Property<long>("ConsignedPaperCount")
                        .HasColumnType("bigint");

                    b.Property<long>("CorrectedPaperCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ExaminationLevelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpectedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Grouped")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGeneral")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastGroupingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MultipleScore")
                        .HasColumnType("bit");

                    b.Property<long>("NotGroupedStudentCount")
                        .HasColumnType("bigint");

                    b.Property<long>("PaperCount")
                        .HasColumnType("bigint");

                    b.Property<long>("PresentPaperCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("Radical")
                        .HasColumnType("bigint");

                    b.Property<string>("RegisterUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("TestGroupCount")
                        .HasColumnType("bigint");

                    b.Property<bool>("UseAnonymity")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ExaminationLevelId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Exam.Entities.TestGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Capacity")
                        .HasColumnType("bigint");

                    b.Property<long>("ConsignedPaperCount")
                        .HasColumnType("bigint");

                    b.Property<long>("CorrectedPaperCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<long>("PaperCount")
                        .HasColumnType("bigint");

                    b.Property<long>("PresentPaperCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("TestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("TestId");

                    b.ToTable("TestGroups");
                });

            modelBuilder.Entity("Exam.Entities.TestGroupCorrector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CorrectorId")
                        .HasColumnType("bigint");

                    b.Property<int>("PaperCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("TestGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CorrectorId");

                    b.HasIndex("TestGroupId");

                    b.ToTable("TestGroupCorrectors");
                });

            modelBuilder.Entity("Exam.Entities.TestGroupSecretary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PaperCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SecretaryId")
                        .HasColumnType("bigint");

                    b.Property<long>("TestGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SecretaryId");

                    b.HasIndex("TestGroupId");

                    b.ToTable("TestGroupSecretaries");
                });

            modelBuilder.Entity("Exam.Entities.TestGroupSupervisor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("bit");

                    b.Property<long>("PaperCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SupervisorId")
                        .HasColumnType("bigint");

                    b.Property<long>("TestGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("TestGroupId");

                    b.ToTable("TestGroupSupervisors");
                });

            modelBuilder.Entity("Exam.Entities.TestLevelSpeciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CourseLevelSpecialityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExaminationLevelSpecialityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("TestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CourseLevelSpecialityId");

                    b.HasIndex("ExaminationLevelSpecialityId");

                    b.HasIndex("TestId");

                    b.ToTable("TestLevelSpecialities");
                });

            modelBuilder.Entity("Exam.Entities.TestScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Radical")
                        .HasColumnType("float");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("TestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("TestScores");
                });

            modelBuilder.Entity("Exam.Entities.Application", b =>
                {
                    b.HasOne("Exam.Entities.Department", null)
                        .WithMany("Applications")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Exam.Entities.Level", "Level")
                        .WithMany("Applications")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.LevelSpeciality", "LevelSpeciality")
                        .WithMany("Applications")
                        .HasForeignKey("LevelSpecialityId");

                    b.HasOne("Exam.Entities.Student", "Student")
                        .WithOne("Application")
                        .HasForeignKey("Exam.Entities.Application", "StudentId");
                });

            modelBuilder.Entity("Exam.Entities.Contest", b =>
                {
                    b.HasOne("Exam.Entities.Paper", "Paper")
                        .WithMany("Contests")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Corrector", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("Correctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.Member", "Member")
                        .WithOne("Corrector")
                        .HasForeignKey("Exam.Entities.Corrector", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Course", b =>
                {
                    b.HasOne("Exam.Entities.Level", "Level")
                        .WithMany("Courses")
                        .HasForeignKey("LevelId");
                });

            modelBuilder.Entity("Exam.Entities.CourseLevelSpeciality", b =>
                {
                    b.HasOne("Exam.Entities.Course", "Course")
                        .WithMany("CourseLevelSpecialities")
                        .HasForeignKey("CourseId");

                    b.HasOne("Exam.Entities.LevelSpeciality", "LevelSpeciality")
                        .WithMany()
                        .HasForeignKey("LevelSpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Department", b =>
                {
                    b.HasOne("Exam.Entities.School", "School")
                        .WithMany("Departments")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Examination", b =>
                {
                    b.HasOne("Exam.Entities.School", "School")
                        .WithMany("Examinations")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.ExaminationDepartment", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("ExaminationDepartments")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Exam.Entities.Examination", "Examination")
                        .WithMany("ExaminationDepartments")
                        .HasForeignKey("ExaminationId");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationLevel", b =>
                {
                    b.HasOne("Exam.Entities.ExaminationDepartment", "ExaminationDepartment")
                        .WithMany("ExaminationLevels")
                        .HasForeignKey("ExaminationDepartmentId");

                    b.HasOne("Exam.Entities.Level", "Level")
                        .WithMany("ExaminationLevels")
                        .HasForeignKey("LevelId");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationLevelSpeciality", b =>
                {
                    b.HasOne("Exam.Entities.ExaminationLevel", "ExaminationLevel")
                        .WithMany("ExaminationLevelSpecialities")
                        .HasForeignKey("ExaminationLevelId");

                    b.HasOne("Exam.Entities.ExaminationSpeciality", "ExaminationSpeciality")
                        .WithMany("ExaminationLevelSpecialities")
                        .HasForeignKey("ExaminationSpecialityId");

                    b.HasOne("Exam.Entities.LevelSpeciality", "LevelSpeciality")
                        .WithMany("ExaminationLevelSpecialities")
                        .HasForeignKey("LevelSpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.ExaminationSpeciality", b =>
                {
                    b.HasOne("Exam.Entities.ExaminationDepartment", "ExaminationDepartment")
                        .WithMany("ExaminationSpecialities")
                        .HasForeignKey("ExaminationDepartmentId");

                    b.HasOne("Exam.Entities.Speciality", "Speciality")
                        .WithMany("ExaminationSpecialities")
                        .HasForeignKey("SpecialityId");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationStudent", b =>
                {
                    b.HasOne("Exam.Entities.ExaminationLevel", "ExaminationLevel")
                        .WithMany("ExaminationStudents")
                        .HasForeignKey("ExaminationLevelId");

                    b.HasOne("Exam.Entities.ExaminationLevelSpeciality", "ExaminationLevelSpeciality")
                        .WithMany("ExaminationStudents")
                        .HasForeignKey("ExaminationLevelSpecialityId");

                    b.HasOne("Exam.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Level", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("Levels")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.LevelSpeciality", b =>
                {
                    b.HasOne("Exam.Entities.Level", "Level")
                        .WithMany("LevelSpecialities")
                        .HasForeignKey("LevelId");

                    b.HasOne("Exam.Entities.Speciality", "Speciality")
                        .WithMany("LevelSpecialities")
                        .HasForeignKey("SpecialityId");
                });

            modelBuilder.Entity("Exam.Entities.Member", b =>
                {
                    b.HasOne("Exam.Entities.School", "School")
                        .WithMany("Members")
                        .HasForeignKey("SchoolId");
                });

            modelBuilder.Entity("Exam.Entities.Paper", b =>
                {
                    b.HasOne("Exam.Entities.ExaminationStudent", "ExaminationStudent")
                        .WithMany("Papers")
                        .HasForeignKey("ExaminationStudentId");

                    b.HasOne("Exam.Entities.TestGroupCorrector", "TestGroupCorrector")
                        .WithMany("Papers")
                        .HasForeignKey("TestGroupCorrectorId");

                    b.HasOne("Exam.Entities.TestGroup", "TestGroup")
                        .WithMany("Papers")
                        .HasForeignKey("TestGroupId");

                    b.HasOne("Exam.Entities.TestGroupSecretary", "TestGroupSecretary")
                        .WithMany("Papers")
                        .HasForeignKey("TestGroupSecretaryId");

                    b.HasOne("Exam.Entities.TestGroupSupervisor", "TestGroupSupervisor")
                        .WithMany()
                        .HasForeignKey("TestGroupSupervisorId");

                    b.HasOne("Exam.Entities.Test", "Test")
                        .WithMany("Papers")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.TestLevelSpeciality", "TestLevelSpeciality")
                        .WithMany("Papers")
                        .HasForeignKey("TestLevelSpecialityId");
                });

            modelBuilder.Entity("Exam.Entities.PaperFile", b =>
                {
                    b.HasOne("Exam.Entities.Paper", "Paper")
                        .WithMany("PaperFiles")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Planner", b =>
                {
                    b.HasOne("Exam.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Principal", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("Principals")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.Member", "Member")
                        .WithOne("Principal")
                        .HasForeignKey("Exam.Entities.Principal", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Room", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("Rooms")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Exam.Entities.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId");

                    b.HasOne("Exam.Entities.School", "School")
                        .WithMany("Rooms")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.School", b =>
                {
                    b.HasOne("Exam.Entities.Member", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalId1");
                });

            modelBuilder.Entity("Exam.Entities.Score", b =>
                {
                    b.HasOne("Exam.Entities.Course", "Course")
                        .WithMany("Scores")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.ScorePaper", b =>
                {
                    b.HasOne("Exam.Entities.Paper", "Paper")
                        .WithMany("ScorePapers")
                        .HasForeignKey("PaperId");

                    b.HasOne("Exam.Entities.TestScore", "TestScore")
                        .WithMany()
                        .HasForeignKey("TestScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Secretary", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("Secretaries")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Speciality", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("Specialities")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Student", b =>
                {
                    b.HasOne("Exam.Entities.Department", null)
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Exam.Entities.Level", "Level")
                        .WithMany("Students")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.LevelSpeciality", "LevelSpeciality")
                        .WithMany("Students")
                        .HasForeignKey("LevelSpecialityId");
                });

            modelBuilder.Entity("Exam.Entities.Supervisor", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("Supervisors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Test", b =>
                {
                    b.HasOne("Exam.Entities.Course", "Course")
                        .WithMany("Tests")
                        .HasForeignKey("CourseId");

                    b.HasOne("Exam.Entities.ExaminationLevel", "ExaminationLevel")
                        .WithMany("Tests")
                        .HasForeignKey("ExaminationLevelId");
                });

            modelBuilder.Entity("Exam.Entities.TestGroup", b =>
                {
                    b.HasOne("Exam.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("Exam.Entities.Test", "Test")
                        .WithMany("Groups")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.TestGroupCorrector", b =>
                {
                    b.HasOne("Exam.Entities.Corrector", "Corrector")
                        .WithMany("TestGroupCorrectors")
                        .HasForeignKey("CorrectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.TestGroup", "TestGroup")
                        .WithMany("TestGroupCorrectors")
                        .HasForeignKey("TestGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.TestGroupSecretary", b =>
                {
                    b.HasOne("Exam.Entities.Secretary", "Secretary")
                        .WithMany()
                        .HasForeignKey("SecretaryId");

                    b.HasOne("Exam.Entities.TestGroup", "TestGroup")
                        .WithMany("TestGroupSecretaries")
                        .HasForeignKey("TestGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.TestGroupSupervisor", b =>
                {
                    b.HasOne("Exam.Entities.Supervisor", "Supervisor")
                        .WithMany("TestGroupSupervisors")
                        .HasForeignKey("SupervisorId");

                    b.HasOne("Exam.Entities.TestGroup", "TestGroup")
                        .WithMany("TestGroupSupervisors")
                        .HasForeignKey("TestGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.TestLevelSpeciality", b =>
                {
                    b.HasOne("Exam.Entities.CourseLevelSpeciality", "CourseLevelSpeciality")
                        .WithMany("TestLevelSpecialities")
                        .HasForeignKey("CourseLevelSpecialityId");

                    b.HasOne("Exam.Entities.ExaminationLevelSpeciality", "ExaminationLevelSpeciality")
                        .WithMany("TestLevelSpecialities")
                        .HasForeignKey("ExaminationLevelSpecialityId");

                    b.HasOne("Exam.Entities.Test", "Test")
                        .WithMany("TestLevelSpecialities")
                        .HasForeignKey("TestId");
                });

            modelBuilder.Entity("Exam.Entities.TestScore", b =>
                {
                    b.HasOne("Exam.Entities.Test", "Test")
                        .WithMany("TestScores")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
