// <auto-generated />
using System;
using Exam.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Exam.Migrations
{
    [DbContext(typeof(PersistenceContext))]
    partial class PersistenceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Exam.Entities.Application", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<char>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasImage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LevelSpecialityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LevelId");

                    b.HasIndex("LevelSpecialityId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Exam.Entities.Contest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<long>("PaperId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Resolved")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaperId");

                    b.ToTable("Contests");
                });

            modelBuilder.Entity("Exam.Entities.Corrector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TestGroupCorrectorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("Correctors");
                });

            modelBuilder.Entity("Exam.Entities.Courses.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChapterText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Coefficient")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGeneral")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MultipleScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PracticalWork")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Radical")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Exam.Entities.Courses.CourseHour", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CourseTeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("EndHour")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Lecture")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("StartHour")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseTeacherId");

                    b.HasIndex("RoomId");

                    b.ToTable("CourseHours");
                });

            modelBuilder.Entity("Exam.Entities.Courses.CourseLevelSpeciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LevelSpecialityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("LevelSpecialityId");

                    b.ToTable("CourseLevelSpecialities");
                });

            modelBuilder.Entity("Exam.Entities.Courses.CourseSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CourseHourId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CourseTeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpectedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpectedStartDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Lecture")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Objective")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Presence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Report")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseHourId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseTeacherId");

                    b.HasIndex("RoomId");

                    b.ToTable("CourseSessions");
                });

            modelBuilder.Entity("Exam.Entities.Courses.CourseTeacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Lecture")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Tutorial")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("CourseTeachers");
                });

            modelBuilder.Entity("Exam.Entities.Courses.Score", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Radical")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Exam.Entities.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Acronym")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCoverImage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasImage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrincipalUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("SchoolId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Exam.Entities.Examination", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpectedStartDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("SchoolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Examinations");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationDepartment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExaminationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ExaminationId");

                    b.ToTable("ExaminationDepartments");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExaminationDepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationDepartmentId");

                    b.HasIndex("LevelId");

                    b.ToTable("ExaminationLevels");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationLevelSpeciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExaminationLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExaminationSpecialityId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LevelSpecialityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationLevelId");

                    b.HasIndex("ExaminationSpecialityId");

                    b.HasIndex("LevelSpecialityId");

                    b.ToTable("ExaminationLevelSpecialities");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationSpeciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExaminationDepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SpecialityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationDepartmentId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("ExaminationSpecialities");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationStudent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExaminationLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExaminationLevelSpecialityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationLevelId");

                    b.HasIndex("ExaminationLevelSpecialityId");

                    b.HasIndex("StudentId");

                    b.ToTable("ExaminationStudents");
                });

            modelBuilder.Entity("Exam.Entities.Level", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("Exam.Entities.LevelSpeciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SpecialityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("LevelSpecialities");
                });

            modelBuilder.Entity("Exam.Entities.Member", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SchoolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Exam.Entities.Paper", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Anonymity")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectorUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContestCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectorComment")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectorUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExaminationStudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroupIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("SecretaryComment")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretaryUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupervisorComment")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupervisorUserId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TestGroupCorrectorId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TestGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TestGroupSecretaryId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TestGroupSupervisorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TestId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TestLevelSpecialityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationStudentId");

                    b.HasIndex("TestGroupCorrectorId");

                    b.HasIndex("TestGroupId");

                    b.HasIndex("TestGroupSecretaryId");

                    b.HasIndex("TestGroupSupervisorId");

                    b.HasIndex("TestId");

                    b.HasIndex("TestLevelSpecialityId");

                    b.ToTable("Papers");
                });

            modelBuilder.Entity("Exam.Entities.PaperFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Corrected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("PaperId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaperId");

                    b.ToTable("PaperFiles");
                });

            modelBuilder.Entity("Exam.Entities.Periods.Semester", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpectedStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("YearId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("YearId");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("Exam.Entities.Periods.SemesterDepartment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Opened")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pending")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SemesterId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("YearDepartmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.HasIndex("YearDepartmentId");

                    b.ToTable("SemesterDepartments");
                });

            modelBuilder.Entity("Exam.Entities.Periods.SemesterLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Opened")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pending")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SemesterDepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("YearLevelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SemesterDepartmentId");

                    b.HasIndex("YearLevelId");

                    b.ToTable("SemesterLevels");
                });

            modelBuilder.Entity("Exam.Entities.Periods.SemesterLevelSpeciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Opened")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pending")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SemesterLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SemesterSpecialityId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("YearLevelSpecialityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SemesterLevelId");

                    b.HasIndex("SemesterSpecialityId");

                    b.HasIndex("YearLevelSpecialityId");

                    b.ToTable("SemesterLevelSpecialities");
                });

            modelBuilder.Entity("Exam.Entities.Periods.SemesterSpeciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Opened")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pending")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SemesterDepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("YearSpecialityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SemesterDepartmentId");

                    b.HasIndex("YearSpecialityId");

                    b.ToTable("SemesterSpecialities");
                });

            modelBuilder.Entity("Exam.Entities.Periods.Year", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpectedStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("SchoolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Years");
                });

            modelBuilder.Entity("Exam.Entities.Periods.YearDepartment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Opened")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pending")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("YearId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("YearId");

                    b.ToTable("YearDepartments");
                });

            modelBuilder.Entity("Exam.Entities.Periods.YearLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Opened")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pending")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("YearDepartmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("YearDepartmentId");

                    b.ToTable("YearLevels");
                });

            modelBuilder.Entity("Exam.Entities.Periods.YearLevelSpeciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LevelSpecialityId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Opened")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pending")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("YearLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("YearSpecialityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LevelSpecialityId");

                    b.HasIndex("YearLevelId");

                    b.HasIndex("YearSpecialityId");

                    b.ToTable("YearLevelSpecialities");
                });

            modelBuilder.Entity("Exam.Entities.Periods.YearSpeciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Opened")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pending")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SpecialityId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("YearDepartmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpecialityId");

                    b.HasIndex("YearDepartmentId");

                    b.ToTable("YearSpecialities");
                });

            modelBuilder.Entity("Exam.Entities.Planner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisterUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("SchoolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Planners");
                });

            modelBuilder.Entity("Exam.Entities.Principal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisterUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("Principals");
                });

            modelBuilder.Entity("Exam.Entities.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("SchoolId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LevelId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Exam.Entities.School", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Acronym")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCoverImage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasImage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PrincipalId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PrincipalId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrincipalUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalId1");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("Exam.Entities.ScorePaper", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PaperId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("TestScoreId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PaperId");

                    b.HasIndex("TestScoreId");

                    b.ToTable("ScorePapers");
                });

            modelBuilder.Entity("Exam.Entities.Secretary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisterUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MemberId");

                    b.ToTable("Secretaries");
                });

            modelBuilder.Entity("Exam.Entities.Speciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Specialities");
                });

            modelBuilder.Entity("Exam.Entities.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<char>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasImage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LevelSpecialityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LevelId");

                    b.HasIndex("LevelSpecialityId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Exam.Entities.Supervisor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MemberId");

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("Exam.Entities.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MemberId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Exam.Entities.Test", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Coefficient")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ConsignedPaperCount")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CorrectedPaperCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExaminationLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpectedStartDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Grouped")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGeneral")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastGroupingDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MultipleScore")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("NotGroupedStudentCount")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PaperCount")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PresentPaperCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Radical")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisterUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<uint>("TestGroupCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseAnonymity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ExaminationLevelId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Exam.Entities.TestGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ConsignedPaperCount")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CorrectedPaperCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PaperCount")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PresentPaperCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("TestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("TestId");

                    b.ToTable("TestGroups");
                });

            modelBuilder.Entity("Exam.Entities.TestGroupCorrector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CorrectorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("TestGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CorrectorId");

                    b.HasIndex("TestGroupId");

                    b.ToTable("TestGroupCorrectors");
                });

            modelBuilder.Entity("Exam.Entities.TestGroupSecretary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SecretaryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TestGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SecretaryId");

                    b.HasIndex("TestGroupId");

                    b.ToTable("TestGroupSecretaries");
                });

            modelBuilder.Entity("Exam.Entities.TestGroupSupervisor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PaperCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SupervisorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TestGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("TestGroupId");

                    b.ToTable("TestGroupSupervisors");
                });

            modelBuilder.Entity("Exam.Entities.TestLevelSpeciality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CourseLevelSpecialityId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExaminationLevelSpecialityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseLevelSpecialityId");

                    b.HasIndex("ExaminationLevelSpecialityId");

                    b.HasIndex("TestId");

                    b.ToTable("TestLevelSpecialities");
                });

            modelBuilder.Entity("Exam.Entities.TestScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Radical")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("TestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("TestScores");
                });

            modelBuilder.Entity("Exam.Entities.Application", b =>
                {
                    b.HasOne("Exam.Entities.Department", null)
                        .WithMany("Applications")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Exam.Entities.Level", "Level")
                        .WithMany("Applications")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.LevelSpeciality", "LevelSpeciality")
                        .WithMany("Applications")
                        .HasForeignKey("LevelSpecialityId");

                    b.HasOne("Exam.Entities.Student", "Student")
                        .WithOne("Application")
                        .HasForeignKey("Exam.Entities.Application", "StudentId");
                });

            modelBuilder.Entity("Exam.Entities.Contest", b =>
                {
                    b.HasOne("Exam.Entities.Paper", "Paper")
                        .WithMany("Contests")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Corrector", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("Correctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.Member", "Member")
                        .WithOne("Corrector")
                        .HasForeignKey("Exam.Entities.Corrector", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Courses.Course", b =>
                {
                    b.HasOne("Exam.Entities.Level", "Level")
                        .WithMany("Courses")
                        .HasForeignKey("LevelId");
                });

            modelBuilder.Entity("Exam.Entities.Courses.CourseHour", b =>
                {
                    b.HasOne("Exam.Entities.Courses.Course", "Course")
                        .WithMany("CourseHours")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.Courses.CourseTeacher", "CourseTeacher")
                        .WithMany("CourseHours")
                        .HasForeignKey("CourseTeacherId");

                    b.HasOne("Exam.Entities.Room", "Room")
                        .WithMany("CourseHours")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("Exam.Entities.Courses.CourseLevelSpeciality", b =>
                {
                    b.HasOne("Exam.Entities.Courses.Course", "Course")
                        .WithMany("CourseLevelSpecialities")
                        .HasForeignKey("CourseId");

                    b.HasOne("Exam.Entities.LevelSpeciality", "LevelSpeciality")
                        .WithMany()
                        .HasForeignKey("LevelSpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Courses.CourseSession", b =>
                {
                    b.HasOne("Exam.Entities.Courses.CourseHour", "CourseHour")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CourseHourId");

                    b.HasOne("Exam.Entities.Courses.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.Courses.CourseTeacher", "CourseTeacher")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CourseTeacherId");

                    b.HasOne("Exam.Entities.Room", "Room")
                        .WithMany("CourseSessions")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("Exam.Entities.Courses.CourseTeacher", b =>
                {
                    b.HasOne("Exam.Entities.Courses.Course", "Course")
                        .WithMany("CourseTeachers")
                        .HasForeignKey("CourseId");

                    b.HasOne("Exam.Entities.Teacher", "Teacher")
                        .WithMany("CourseTeachers")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("Exam.Entities.Courses.Score", b =>
                {
                    b.HasOne("Exam.Entities.Courses.Course", "Course")
                        .WithMany("Scores")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Department", b =>
                {
                    b.HasOne("Exam.Entities.School", "School")
                        .WithMany("Departments")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Examination", b =>
                {
                    b.HasOne("Exam.Entities.School", "School")
                        .WithMany("Examinations")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.ExaminationDepartment", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("ExaminationDepartments")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Exam.Entities.Examination", "Examination")
                        .WithMany("ExaminationDepartments")
                        .HasForeignKey("ExaminationId");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationLevel", b =>
                {
                    b.HasOne("Exam.Entities.ExaminationDepartment", "ExaminationDepartment")
                        .WithMany("ExaminationLevels")
                        .HasForeignKey("ExaminationDepartmentId");

                    b.HasOne("Exam.Entities.Level", "Level")
                        .WithMany("ExaminationLevels")
                        .HasForeignKey("LevelId");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationLevelSpeciality", b =>
                {
                    b.HasOne("Exam.Entities.ExaminationLevel", "ExaminationLevel")
                        .WithMany("ExaminationLevelSpecialities")
                        .HasForeignKey("ExaminationLevelId");

                    b.HasOne("Exam.Entities.ExaminationSpeciality", "ExaminationSpeciality")
                        .WithMany("ExaminationLevelSpecialities")
                        .HasForeignKey("ExaminationSpecialityId");

                    b.HasOne("Exam.Entities.LevelSpeciality", "LevelSpeciality")
                        .WithMany("ExaminationLevelSpecialities")
                        .HasForeignKey("LevelSpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.ExaminationSpeciality", b =>
                {
                    b.HasOne("Exam.Entities.ExaminationDepartment", "ExaminationDepartment")
                        .WithMany("ExaminationSpecialities")
                        .HasForeignKey("ExaminationDepartmentId");

                    b.HasOne("Exam.Entities.Speciality", "Speciality")
                        .WithMany("ExaminationSpecialities")
                        .HasForeignKey("SpecialityId");
                });

            modelBuilder.Entity("Exam.Entities.ExaminationStudent", b =>
                {
                    b.HasOne("Exam.Entities.ExaminationLevel", "ExaminationLevel")
                        .WithMany("ExaminationStudents")
                        .HasForeignKey("ExaminationLevelId");

                    b.HasOne("Exam.Entities.ExaminationLevelSpeciality", "ExaminationLevelSpeciality")
                        .WithMany("ExaminationStudents")
                        .HasForeignKey("ExaminationLevelSpecialityId");

                    b.HasOne("Exam.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Level", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("Levels")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.LevelSpeciality", b =>
                {
                    b.HasOne("Exam.Entities.Level", "Level")
                        .WithMany("LevelSpecialities")
                        .HasForeignKey("LevelId");

                    b.HasOne("Exam.Entities.Speciality", "Speciality")
                        .WithMany("LevelSpecialities")
                        .HasForeignKey("SpecialityId");
                });

            modelBuilder.Entity("Exam.Entities.Member", b =>
                {
                    b.HasOne("Exam.Entities.School", "School")
                        .WithMany("Members")
                        .HasForeignKey("SchoolId");
                });

            modelBuilder.Entity("Exam.Entities.Paper", b =>
                {
                    b.HasOne("Exam.Entities.ExaminationStudent", "ExaminationStudent")
                        .WithMany("Papers")
                        .HasForeignKey("ExaminationStudentId");

                    b.HasOne("Exam.Entities.TestGroupCorrector", "TestGroupCorrector")
                        .WithMany("Papers")
                        .HasForeignKey("TestGroupCorrectorId");

                    b.HasOne("Exam.Entities.TestGroup", "TestGroup")
                        .WithMany("Papers")
                        .HasForeignKey("TestGroupId");

                    b.HasOne("Exam.Entities.TestGroupSecretary", "TestGroupSecretary")
                        .WithMany("Papers")
                        .HasForeignKey("TestGroupSecretaryId");

                    b.HasOne("Exam.Entities.TestGroupSupervisor", "TestGroupSupervisor")
                        .WithMany()
                        .HasForeignKey("TestGroupSupervisorId");

                    b.HasOne("Exam.Entities.Test", "Test")
                        .WithMany("Papers")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.TestLevelSpeciality", "TestLevelSpeciality")
                        .WithMany("Papers")
                        .HasForeignKey("TestLevelSpecialityId");
                });

            modelBuilder.Entity("Exam.Entities.PaperFile", b =>
                {
                    b.HasOne("Exam.Entities.Paper", "Paper")
                        .WithMany("PaperFiles")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Periods.Semester", b =>
                {
                    b.HasOne("Exam.Entities.Periods.Year", "Year")
                        .WithMany("Semesters")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Periods.SemesterDepartment", b =>
                {
                    b.HasOne("Exam.Entities.Periods.Semester", "Semester")
                        .WithMany("SemesterDepartments")
                        .HasForeignKey("SemesterId");

                    b.HasOne("Exam.Entities.Periods.YearDepartment", "YearDepartment")
                        .WithMany("SemesterDepartments")
                        .HasForeignKey("YearDepartmentId");
                });

            modelBuilder.Entity("Exam.Entities.Periods.SemesterLevel", b =>
                {
                    b.HasOne("Exam.Entities.Periods.SemesterDepartment", "SemesterDepartment")
                        .WithMany("SemesterLevels")
                        .HasForeignKey("SemesterDepartmentId");

                    b.HasOne("Exam.Entities.Periods.YearLevel", "YearLevel")
                        .WithMany("SemesterLevels")
                        .HasForeignKey("YearLevelId");
                });

            modelBuilder.Entity("Exam.Entities.Periods.SemesterLevelSpeciality", b =>
                {
                    b.HasOne("Exam.Entities.Periods.SemesterLevel", "SemesterLevel")
                        .WithMany("SemesterLevelSpecialities")
                        .HasForeignKey("SemesterLevelId");

                    b.HasOne("Exam.Entities.Periods.SemesterSpeciality", "SemesterSpeciality")
                        .WithMany("SemesterLevelSpecialities")
                        .HasForeignKey("SemesterSpecialityId");

                    b.HasOne("Exam.Entities.Periods.YearLevelSpeciality", "YearLevelSpeciality")
                        .WithMany("SemesterLevelSpecialities")
                        .HasForeignKey("YearLevelSpecialityId");
                });

            modelBuilder.Entity("Exam.Entities.Periods.SemesterSpeciality", b =>
                {
                    b.HasOne("Exam.Entities.Periods.SemesterDepartment", "SemesterDepartment")
                        .WithMany("SemesterSpecialities")
                        .HasForeignKey("SemesterDepartmentId");

                    b.HasOne("Exam.Entities.Periods.YearSpeciality", "YearSpeciality")
                        .WithMany("SemesterSpecialities")
                        .HasForeignKey("YearSpecialityId");
                });

            modelBuilder.Entity("Exam.Entities.Periods.Year", b =>
                {
                    b.HasOne("Exam.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Periods.YearDepartment", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Exam.Entities.Periods.Year", "Year")
                        .WithMany("YearDepartments")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Periods.YearLevel", b =>
                {
                    b.HasOne("Exam.Entities.Level", "Level")
                        .WithMany("YearLevels")
                        .HasForeignKey("LevelId");

                    b.HasOne("Exam.Entities.Periods.YearDepartment", "YearDepartment")
                        .WithMany("YearLevels")
                        .HasForeignKey("YearDepartmentId");
                });

            modelBuilder.Entity("Exam.Entities.Periods.YearLevelSpeciality", b =>
                {
                    b.HasOne("Exam.Entities.LevelSpeciality", "LevelSpeciality")
                        .WithMany("YearLevelSpecialities")
                        .HasForeignKey("LevelSpecialityId");

                    b.HasOne("Exam.Entities.Periods.YearLevel", "YearLevel")
                        .WithMany("YearLevelSpecialities")
                        .HasForeignKey("YearLevelId");

                    b.HasOne("Exam.Entities.Periods.YearSpeciality", "YearSpeciality")
                        .WithMany("YearLevelSpecialities")
                        .HasForeignKey("YearSpecialityId");
                });

            modelBuilder.Entity("Exam.Entities.Periods.YearSpeciality", b =>
                {
                    b.HasOne("Exam.Entities.Speciality", "Speciality")
                        .WithMany("YearSpecialities")
                        .HasForeignKey("SpecialityId");

                    b.HasOne("Exam.Entities.Periods.YearDepartment", "YearDepartment")
                        .WithMany("YearSpecialities")
                        .HasForeignKey("YearDepartmentId");
                });

            modelBuilder.Entity("Exam.Entities.Planner", b =>
                {
                    b.HasOne("Exam.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Principal", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("Principals")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.Member", "Member")
                        .WithOne("Principal")
                        .HasForeignKey("Exam.Entities.Principal", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Room", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("Rooms")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Exam.Entities.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId");

                    b.HasOne("Exam.Entities.School", "School")
                        .WithMany("Rooms")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.School", b =>
                {
                    b.HasOne("Exam.Entities.Member", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalId1");
                });

            modelBuilder.Entity("Exam.Entities.ScorePaper", b =>
                {
                    b.HasOne("Exam.Entities.Paper", "Paper")
                        .WithMany("ScorePapers")
                        .HasForeignKey("PaperId");

                    b.HasOne("Exam.Entities.TestScore", "TestScore")
                        .WithMany()
                        .HasForeignKey("TestScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Secretary", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("Secretaries")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Speciality", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("Specialities")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Student", b =>
                {
                    b.HasOne("Exam.Entities.Department", null)
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Exam.Entities.Level", "Level")
                        .WithMany("Students")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.LevelSpeciality", "LevelSpeciality")
                        .WithMany("Students")
                        .HasForeignKey("LevelSpecialityId");
                });

            modelBuilder.Entity("Exam.Entities.Supervisor", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("Supervisors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Teacher", b =>
                {
                    b.HasOne("Exam.Entities.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.Test", b =>
                {
                    b.HasOne("Exam.Entities.Courses.Course", "Course")
                        .WithMany("Tests")
                        .HasForeignKey("CourseId");

                    b.HasOne("Exam.Entities.ExaminationLevel", "ExaminationLevel")
                        .WithMany("Tests")
                        .HasForeignKey("ExaminationLevelId");
                });

            modelBuilder.Entity("Exam.Entities.TestGroup", b =>
                {
                    b.HasOne("Exam.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("Exam.Entities.Test", "Test")
                        .WithMany("Groups")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.TestGroupCorrector", b =>
                {
                    b.HasOne("Exam.Entities.Corrector", "Corrector")
                        .WithMany("TestGroupCorrectors")
                        .HasForeignKey("CorrectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Entities.TestGroup", "TestGroup")
                        .WithMany("TestGroupCorrectors")
                        .HasForeignKey("TestGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.TestGroupSecretary", b =>
                {
                    b.HasOne("Exam.Entities.Secretary", "Secretary")
                        .WithMany()
                        .HasForeignKey("SecretaryId");

                    b.HasOne("Exam.Entities.TestGroup", "TestGroup")
                        .WithMany("TestGroupSecretaries")
                        .HasForeignKey("TestGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.TestGroupSupervisor", b =>
                {
                    b.HasOne("Exam.Entities.Supervisor", "Supervisor")
                        .WithMany("TestGroupSupervisors")
                        .HasForeignKey("SupervisorId");

                    b.HasOne("Exam.Entities.TestGroup", "TestGroup")
                        .WithMany("TestGroupSupervisors")
                        .HasForeignKey("TestGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exam.Entities.TestLevelSpeciality", b =>
                {
                    b.HasOne("Exam.Entities.Courses.CourseLevelSpeciality", "CourseLevelSpeciality")
                        .WithMany("TestLevelSpecialities")
                        .HasForeignKey("CourseLevelSpecialityId");

                    b.HasOne("Exam.Entities.ExaminationLevelSpeciality", "ExaminationLevelSpeciality")
                        .WithMany("TestLevelSpecialities")
                        .HasForeignKey("ExaminationLevelSpecialityId");

                    b.HasOne("Exam.Entities.Test", "Test")
                        .WithMany("TestLevelSpecialities")
                        .HasForeignKey("TestId");
                });

            modelBuilder.Entity("Exam.Entities.TestScore", b =>
                {
                    b.HasOne("Exam.Entities.Test", "Test")
                        .WithMany("TestScores")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
