export * from './school.entity';
export * from './department.entity';
export * from './level.entity';
export * from './level-speciality.entity';
export * from './course.entity';
export * from './score.entity';
export * from './room.entity';
export * from './speciality.entity';
export * from './course-level-speciality.entity';
